apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pixy.name }}
spec:
  selector:
    app: {{ .Values.pixy.name }}
  type: LoadBalancer
  ports:
    - name: grpc
      protocol: TCP
      port: 19091
      targetPort: 19091
    - name: http
      protocol: TCP
      port: 19092
      targetPort: 19092