apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.confluent.name }}
spec:
  selector:
    app: {{ .Values.confluent.name }}
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
