apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}
spec:
  selector:
    app: {{ .Values.kafka.name }}
  type: ClusterIP
  clusterIP: {{ .Values.kafka.service.clusterIP }}
  ports:
    - name: broker
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181
