apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zk.name }}
spec:
  selector:
    app: {{ .Values.zk.name }}
  type: ClusterIP
  clusterIP: {{ .Values.zk.service.clusterIP }}
  ports:
    - name: port-2181
      port: 2181
      protocol: TCP 
    - name: port-2888
      port: 2888
      protocol: TCP 
    - name: port-3888
      port: 3888
      protocol: TCP 
